const String interestingPlaces = 'Интересные места',
    interesting = 'Интересные',
    places = ' места',
    listInterestingPlaces = 'Список интересных мест',
    category = 'Категория',
    aroundTheClock = 'круглосуточно',
    buildARoute = 'построить маршрут',
    schedule = 'Запланировать',
    toFavorites = 'В Избранное';
